apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        hosts {
           192.168.65.254 host.minikube.internal
           fallthrough
        }
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
        hosts custom.hosts {
              10.101.41.227 keycloak.local
              fallthrough
            }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    log\n    errors\n    health {\n       lameduck 5s\n    }\n    ready\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n       pods insecure\n       fallthrough in-addr.arpa ip6.arpa\n       ttl 30\n    }\n    prometheus :9153\n    hosts {\n       192.168.65.254 host.minikube.internal\n       fallthrough\n    }\n    forward . /etc/resolv.conf {\n       max_concurrent 1000\n    }\n    cache 30\n    loop\n    reload\n    loadbalance\n    hosts custom.hosts {\n          10.101.41.227 keycloak.local\n          fallthrough\n        }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2025-01-19T16:39:29Z","managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{}},"manager":"kubeadm","operation":"Update","time":"2025-01-19T16:39:29Z"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{"f:Corefile":{}},"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2025-01-19T17:54:20Z"}],"name":"coredns","namespace":"kube-system","selfLink":"/api/v1/namespaces/kube-system/configmaps/coredns","uid":"8ac7a6ef-a41b-4d0a-9b15-3278d0cbd838"}}
  creationTimestamp: "2025-01-19T16:39:29Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "2825"
  uid: 8ac7a6ef-a41b-4d0a-9b15-3278d0cbd838
